-- APESO Skill Data
-- Maps AP item offsets to skill names for display
-- Base ID: 152100 (eso_skill_unlock_id)

APESO_SkillData = APESO_SkillData or {}

-- Skill definitions by category
-- Each entry: { offset = X, name = "Skill Name", passive = true/false }
APESO_SkillData.Categories = {
    ["Ardent Flame"] = {
        { offset = 0, name = "Dragonknight Standard", passive = false, ultimate = true },
        { offset = 1, name = "Shifting Standard", passive = false, morph = true },
        { offset = 2, name = "Standard of Might", passive = false, morph = true },
        { offset = 3, name = "Searing Strike", passive = false },
        { offset = 4, name = "Venomous Claw", passive = false, morph = true },
        { offset = 5, name = "Burning Embers", passive = false, morph = true },
        { offset = 6, name = "Fiery Breath", passive = false },
        { offset = 7, name = "Noxious Breath", passive = false, morph = true },
        { offset = 8, name = "Engulfing Flames", passive = false, morph = true },
        { offset = 9, name = "Fiery Grip", passive = false },
        { offset = 10, name = "Chains of Devastation", passive = false, morph = true },
        { offset = 11, name = "Unrelenting Grip", passive = false, morph = true },
        { offset = 12, name = "Inferno", passive = false },
        { offset = 13, name = "Flames of Oblivion", passive = false, morph = true },
        { offset = 14, name = "Cauterize", passive = false, morph = true },
        { offset = 15, name = "Combustion", passive = true },
        { offset = 16, name = "Warmth", passive = true },
        { offset = 17, name = "Searing Heat", passive = true },
        { offset = 18, name = "World in Ruin", passive = true },
    },
    ["Draconic Power"] = {
        { offset = 19, name = "Dragon Leap", passive = false, ultimate = true },
        { offset = 20, name = "Take Flight", passive = false, morph = true },
        { offset = 21, name = "Ferocious Leap", passive = false, morph = true },
        { offset = 22, name = "Spiked Armor", passive = false },
        { offset = 23, name = "Hardened Armor", passive = false, morph = true },
        { offset = 24, name = "Volatile Armor", passive = false, morph = true },
        { offset = 25, name = "Dark Talons", passive = false },
        { offset = 26, name = "Burning Talons", passive = false, morph = true },
        { offset = 27, name = "Choking Talons", passive = false, morph = true },
        { offset = 28, name = "Dragon Blood", passive = false },
        { offset = 29, name = "Green Dragon Blood", passive = false, morph = true },
        { offset = 30, name = "Coagulating Blood", passive = false, morph = true },
        { offset = 31, name = "Protective Scale", passive = false },
        { offset = 32, name = "Protective Plate", passive = false, morph = true },
        { offset = 33, name = "Dragon Fire Scale", passive = false, morph = true },
        { offset = 34, name = "Inhale", passive = false },
        { offset = 35, name = "Deep Breath", passive = false, morph = true },
        { offset = 36, name = "Draw Essence", passive = false, morph = true },
        { offset = 37, name = "Iron Skin", passive = true },
        { offset = 38, name = "Burning Heart", passive = true },
        { offset = 39, name = "Elder Dragon", passive = true },
        { offset = 40, name = "Scaled Armor", passive = true },
    },
    ["Earthen Heart"] = {
        { offset = 41, name = "Magma Armor", passive = false, ultimate = true },
        { offset = 42, name = "Magma Shell", passive = false, morph = true },
        { offset = 43, name = "Corrosive Armor", passive = false, morph = true },
        { offset = 44, name = "Stonefist", passive = false },
        { offset = 45, name = "Obsidian Shard", passive = false, morph = true },
        { offset = 46, name = "Stone Giant", passive = false, morph = true },
        { offset = 47, name = "Molten Weapons", passive = false },
        { offset = 48, name = "Igneous Weapons", passive = false, morph = true },
        { offset = 49, name = "Molten Armaments", passive = false, morph = true },
        { offset = 50, name = "Obsidian Shield", passive = false },
        { offset = 51, name = "Igneous Shield", passive = false, morph = true },
        { offset = 52, name = "Fragmented Shield", passive = false, morph = true },
        { offset = 53, name = "Petrify", passive = false },
        { offset = 54, name = "Fossilize", passive = false, morph = true },
        { offset = 55, name = "Shattering Rocks", passive = false, morph = true },
        { offset = 56, name = "Ash Cloud", passive = false },
        { offset = 57, name = "Cinder Storm", passive = false, morph = true },
        { offset = 58, name = "Eruption", passive = false, morph = true },
        { offset = 59, name = "Eternal Mountain", passive = true },
        { offset = 60, name = "Battle Roar", passive = true },
        { offset = 61, name = "Mountain's Blessing", passive = true },
        { offset = 62, name = "Helping Hands", passive = true },
    },
    ["Dark Magic"] = {
        { offset = 63, name = "Negate Magic", passive = false, ultimate = true },
        { offset = 64, name = "Suppression Field", passive = false, morph = true },
        { offset = 65, name = "Absorption Field", passive = false, morph = true },
        { offset = 66, name = "Crystal Shard", passive = false },
        { offset = 67, name = "Crystal Fragments", passive = false, morph = true },
        { offset = 68, name = "Crystal Weapon", passive = false, morph = true },
        { offset = 69, name = "Encase", passive = false },
        { offset = 70, name = "Shattering Prison", passive = false, morph = true },
        { offset = 71, name = "Restraining Prison", passive = false, morph = true },
        { offset = 72, name = "Rune Prison", passive = false },
        { offset = 73, name = "Rune Cage", passive = false, morph = true },
        { offset = 74, name = "Defensive Rune", passive = false, morph = true },
        { offset = 75, name = "Dark Exchange", passive = false },
        { offset = 76, name = "Dark Deal", passive = false, morph = true },
        { offset = 77, name = "Dark Conversion", passive = false, morph = true },
        { offset = 78, name = "Daedric Mines", passive = false },
        { offset = 79, name = "Daedric Minefield", passive = false, morph = true },
        { offset = 80, name = "Daedric Tomb", passive = false, morph = true },
        { offset = 81, name = "Unholy Knowledge", passive = true },
        { offset = 82, name = "Blood Magic", passive = true },
        { offset = 83, name = "Persistence", passive = true },
        { offset = 84, name = "Exploitation", passive = true },
    },
    ["Daedric Summoning"] = {
        { offset = 85, name = "Summon Storm Atronach", passive = false, ultimate = true },
        { offset = 86, name = "Greater Storm Atronach", passive = false, morph = true },
        { offset = 87, name = "Summon Charged Atronach", passive = false, morph = true },
        { offset = 88, name = "Unstable Familiar", passive = false },
        { offset = 89, name = "Unstable Clannfear", passive = false, morph = true },
        { offset = 90, name = "Volatile Familiar", passive = false, morph = true },
        { offset = 91, name = "Daedric Curse", passive = false },
        { offset = 92, name = "Daedric Prey", passive = false, morph = true },
        { offset = 93, name = "Haunting Curse", passive = false, morph = true },
        { offset = 94, name = "Summon Winged Twilight", passive = false },
        { offset = 95, name = "Summon Twilight Tormentor", passive = false, morph = true },
        { offset = 96, name = "Summon Twilight Matriarch", passive = false, morph = true },
        { offset = 97, name = "Conjured Ward", passive = false },
        { offset = 98, name = "Hardened Ward", passive = false, morph = true },
        { offset = 99, name = "Empowered Ward", passive = false, morph = true },
        { offset = 100, name = "Bound Armor", passive = false },
        { offset = 101, name = "Bound Armaments", passive = false, morph = true },
        { offset = 102, name = "Bound Aegis", passive = false, morph = true },
        { offset = 103, name = "Rebate", passive = true },
        { offset = 104, name = "Power Stone", passive = true },
        { offset = 105, name = "Daedric Protection", passive = true },
        { offset = 106, name = "Expert Summoner", passive = true },
    },
    ["Storm Calling"] = {
        { offset = 107, name = "Overload", passive = false, ultimate = true },
        { offset = 108, name = "Energy Overload", passive = false, morph = true },
        { offset = 109, name = "Power Overload", passive = false, morph = true },
        { offset = 110, name = "Mages' Fury", passive = false },
        { offset = 111, name = "Mages' Wrath", passive = false, morph = true },
        { offset = 112, name = "Endless Fury", passive = false, morph = true },
        { offset = 113, name = "Lightning Form", passive = false },
        { offset = 114, name = "Hurricane", passive = false, morph = true },
        { offset = 115, name = "Boundless Storm", passive = false, morph = true },
        { offset = 116, name = "Lightning Splash", passive = false },
        { offset = 117, name = "Liquid Lightning", passive = false, morph = true },
        { offset = 118, name = "Lightning Flood", passive = false, morph = true },
        { offset = 119, name = "Surge", passive = false },
        { offset = 120, name = "Power Surge", passive = false, morph = true },
        { offset = 121, name = "Critical Surge", passive = false, morph = true },
        { offset = 122, name = "Bolt Escape", passive = false },
        { offset = 123, name = "Streak", passive = false, morph = true },
        { offset = 124, name = "Ball of Lightning", passive = false, morph = true },
        { offset = 125, name = "Capacitor", passive = true },
        { offset = 126, name = "Energized", passive = true },
        { offset = 127, name = "Amplitude", passive = true },
        { offset = 128, name = "Expert Mage", passive = true },
    },
    ["Assassination"] = {
        { offset = 129, name = "Death Stroke", passive = false, ultimate = true },
        { offset = 130, name = "Incapacitating Strike", passive = false, morph = true },
        { offset = 131, name = "Soul Harvest", passive = false, morph = true },
        { offset = 132, name = "Assassin's Blade", passive = false },
        { offset = 133, name = "Killer's Blade", passive = false, morph = true },
        { offset = 134, name = "Impale", passive = false, morph = true },
        { offset = 135, name = "Teleport Strike", passive = false },
        { offset = 136, name = "Lotus Fan", passive = false, morph = true },
        { offset = 137, name = "Ambush", passive = false, morph = true },
        { offset = 138, name = "Blur", passive = false },
        { offset = 139, name = "Mirage", passive = false, morph = true },
        { offset = 140, name = "Double Take", passive = false, morph = true },
        { offset = 141, name = "Mark Target", passive = false },
        { offset = 142, name = "Piercing Mark", passive = false, morph = true },
        { offset = 143, name = "Reaper's Mark", passive = false, morph = true },
        { offset = 144, name = "Grim Focus", passive = false },
        { offset = 145, name = "Relentless Focus", passive = false, morph = true },
        { offset = 146, name = "Merciless Resolve", passive = false, morph = true },
        { offset = 147, name = "Master Assassin", passive = true },
        { offset = 148, name = "Executioner", passive = true },
        { offset = 149, name = "Pressure Points", passive = true },
        { offset = 150, name = "Hemorrhage", passive = true },
    },
    ["Shadow"] = {
        { offset = 151, name = "Consuming Darkness", passive = false, ultimate = true },
        { offset = 152, name = "Bolstering Darkness", passive = false, morph = true },
        { offset = 153, name = "Veil of Blades", passive = false, morph = true },
        { offset = 154, name = "Shadow Cloak", passive = false },
        { offset = 155, name = "Shadowy Disguise", passive = false, morph = true },
        { offset = 156, name = "Dark Cloak", passive = false, morph = true },
        { offset = 157, name = "Veiled Strike", passive = false },
        { offset = 158, name = "Concealed Weapon", passive = false, morph = true },
        { offset = 159, name = "Surprise Attack", passive = false, morph = true },
        { offset = 160, name = "Path of Darkness", passive = false },
        { offset = 161, name = "Twisting Path", passive = false, morph = true },
        { offset = 162, name = "Refreshing Path", passive = false, morph = true },
        { offset = 163, name = "Aspect of Terror", passive = false },
        { offset = 164, name = "Mass Hysteria", passive = false, morph = true },
        { offset = 165, name = "Manifestation of Terror", passive = false, morph = true },
        { offset = 166, name = "Summon Shade", passive = false },
        { offset = 167, name = "Dark Shade", passive = false, morph = true },
        { offset = 168, name = "Shadow Image", passive = false, morph = true },
        { offset = 169, name = "Refreshing Shadows", passive = true },
        { offset = 170, name = "Shadow Barrier", passive = true },
        { offset = 171, name = "Dark Vigor", passive = true },
        { offset = 172, name = "Dark Veil", passive = true },
    },
    ["Siphoning"] = {
        { offset = 173, name = "Soul Shred", passive = false, ultimate = true },
        { offset = 174, name = "Soul Siphon", passive = false, morph = true },
        { offset = 175, name = "Soul Tether", passive = false, morph = true },
        { offset = 176, name = "Strife", passive = false },
        { offset = 177, name = "Funnel Health", passive = false, morph = true },
        { offset = 178, name = "Swallow Soul", passive = false, morph = true },
        { offset = 179, name = "Agony", passive = false },
        { offset = 180, name = "Prolonged Suffering", passive = false, morph = true },
        { offset = 181, name = "Malefic Wreath", passive = false, morph = true },
        { offset = 182, name = "Cripple", passive = false },
        { offset = 183, name = "Debilitate", passive = false, morph = true },
        { offset = 184, name = "Crippling Grasp", passive = false, morph = true },
        { offset = 185, name = "Siphoning Strikes", passive = false },
        { offset = 186, name = "Leeching Strikes", passive = false, morph = true },
        { offset = 187, name = "Siphoning Attacks", passive = false, morph = true },
        { offset = 188, name = "Drain Power", passive = false },
        { offset = 189, name = "Power Extraction", passive = false, morph = true },
        { offset = 190, name = "Sap Essence", passive = false, morph = true },
        { offset = 191, name = "Catalyst", passive = true },
        { offset = 192, name = "Magicka Flood", passive = true },
        { offset = 193, name = "Soul Siphoner", passive = true },
        { offset = 194, name = "Transfer", passive = true },
    },
    -- Templar Skills
    ["Aedric Spear"] = {
        { offset = 195, name = "Radial Sweep", passive = false, ultimate = true },
        { offset = 196, name = "Empowering Sweep", passive = false, morph = true },
        { offset = 197, name = "Crescent Sweep", passive = false, morph = true },
        { offset = 198, name = "Puncturing Strikes", passive = false },
        { offset = 199, name = "Biting Jabs", passive = false, morph = true },
        { offset = 200, name = "Puncturing Sweep", passive = false, morph = true },
        { offset = 201, name = "Piercing Javelin", passive = false },
        { offset = 202, name = "Aurora Javelin", passive = false, morph = true },
        { offset = 203, name = "Binding Javelin", passive = false, morph = true },
        { offset = 204, name = "Focused Charge", passive = false },
        { offset = 205, name = "Explosive Charge", passive = false, morph = true },
        { offset = 206, name = "Toppling Charge", passive = false, morph = true },
        { offset = 207, name = "Spear Shards", passive = false },
        { offset = 208, name = "Luminous Shards", passive = false, morph = true },
        { offset = 209, name = "Blazing Spear", passive = false, morph = true },
        { offset = 210, name = "Sun Shield", passive = false },
        { offset = 211, name = "Radiant Ward", passive = false, morph = true },
        { offset = 212, name = "Blazing Shield", passive = false, morph = true },
        { offset = 213, name = "Piercing Spear", passive = true },
        { offset = 214, name = "Spear Wall", passive = true },
        { offset = 215, name = "Burning Light", passive = true },
        { offset = 216, name = "Balanced Warrior", passive = true },
    },
    ["Dawn's Wrath"] = {
        { offset = 217, name = "Nova", passive = false, ultimate = true },
        { offset = 218, name = "Solar Prison", passive = false, morph = true },
        { offset = 219, name = "Solar Disturbance", passive = false, morph = true },
        { offset = 220, name = "Sun Fire", passive = false },
        { offset = 221, name = "Vampire's Bane", passive = false, morph = true },
        { offset = 222, name = "Reflective Light", passive = false, morph = true },
        { offset = 223, name = "Solar Flare", passive = false },
        { offset = 224, name = "Dark Flare", passive = false, morph = true },
        { offset = 225, name = "Solar Barrage", passive = false, morph = true },
        { offset = 226, name = "Backlash", passive = false },
        { offset = 227, name = "Power of the Light", passive = false, morph = true },
        { offset = 228, name = "Purifying Light", passive = false, morph = true },
        { offset = 229, name = "Eclipse", passive = false },
        { offset = 230, name = "Total Dark", passive = false, morph = true },
        { offset = 231, name = "Unstable Core", passive = false, morph = true },
        { offset = 232, name = "Radiant Destruction", passive = false },
        { offset = 233, name = "Radiant Glory", passive = false, morph = true },
        { offset = 234, name = "Radiant Oppression", passive = false, morph = true },
        { offset = 235, name = "Enduring Rays", passive = true },
        { offset = 236, name = "Prism", passive = true },
        { offset = 237, name = "Illuminate", passive = true },
        { offset = 238, name = "Restoring Spirit", passive = true },
    },
    ["Restoring Light"] = {
        { offset = 239, name = "Rite of Passage", passive = false, ultimate = true },
        { offset = 240, name = "Remembrance", passive = false, morph = true },
        { offset = 241, name = "Practiced Incantation", passive = false, morph = true },
        { offset = 242, name = "Rushed Ceremony", passive = false },
        { offset = 243, name = "Honor the Dead", passive = false, morph = true },
        { offset = 244, name = "Breath of Life", passive = false, morph = true },
        { offset = 245, name = "Healing Ritual", passive = false },
        { offset = 246, name = "Ritual of Rebirth", passive = false, morph = true },
        { offset = 247, name = "Hasty Prayer", passive = false, morph = true },
        { offset = 248, name = "Restoring Aura", passive = false },
        { offset = 249, name = "Radiant Aura", passive = false, morph = true },
        { offset = 250, name = "Cleansing Ritual", passive = false },
        { offset = 251, name = "Ritual of Retribution", passive = false, morph = true },
        { offset = 252, name = "Extended Ritual", passive = false, morph = true },
        { offset = 253, name = "Rune Focus", passive = false },
        { offset = 254, name = "Channeled Focus", passive = false, morph = true },
        { offset = 255, name = "Restoring Focus", passive = false, morph = true },
        { offset = 256, name = "Mending", passive = true },
        { offset = 257, name = "Sacred Ground", passive = true },
        { offset = 258, name = "Light Weaver", passive = true },
        { offset = 259, name = "Master Ritualist", passive = true },
    },
    -- Warden Skills
    ["Winter's Embrace"] = {
        { offset = 260, name = "Sleet Storm", passive = false, ultimate = true },
        { offset = 261, name = "Northern Storm", passive = false, morph = true },
        { offset = 262, name = "Permafrost", passive = false, morph = true },
        { offset = 263, name = "Frost Cloak", passive = false },
        { offset = 264, name = "Expansive Frost Cloak", passive = false, morph = true },
        { offset = 265, name = "Ice Fortress", passive = false, morph = true },
        { offset = 266, name = "Impaling Shards", passive = false },
        { offset = 267, name = "Gripping Shards", passive = false, morph = true },
        { offset = 268, name = "Winter's Revenge", passive = false, morph = true },
        { offset = 269, name = "Arctic Wind", passive = false },
        { offset = 270, name = "Polar Wind", passive = false, morph = true },
        { offset = 271, name = "Arctic Blast", passive = false, morph = true },
        { offset = 272, name = "Crystallized Shield", passive = false },
        { offset = 273, name = "Crystallized Slab", passive = false, morph = true },
        { offset = 274, name = "Shimmering Shield", passive = false, morph = true },
        { offset = 275, name = "Frozen Gate", passive = false },
        { offset = 276, name = "Frozen Device", passive = false, morph = true },
        { offset = 277, name = "Frozen Retreat", passive = false, morph = true },
        { offset = 278, name = "Glacial Presence", passive = true },
        { offset = 279, name = "Frozen Armor", passive = true },
        { offset = 280, name = "Icy Aura", passive = true },
        { offset = 281, name = "Piercing Cold", passive = true },
    },
    ["Green Balance"] = {
        { offset = 282, name = "Secluded Grove", passive = false, ultimate = true },
        { offset = 283, name = "Enchanted Forest", passive = false, morph = true },
        { offset = 284, name = "Healing Thicket", passive = false, morph = true },
        { offset = 285, name = "Fungal Growth", passive = false },
        { offset = 286, name = "Enchanted Growth", passive = false, morph = true },
        { offset = 287, name = "Soothing Spores", passive = false, morph = true },
        { offset = 288, name = "Healing Seed", passive = false },
        { offset = 289, name = "Budding Seeds", passive = false, morph = true },
        { offset = 290, name = "Corrupting Pollen", passive = false, morph = true },
        { offset = 291, name = "Living Vines", passive = false },
        { offset = 292, name = "Leeching Vines", passive = false, morph = true },
        { offset = 293, name = "Living Trellis", passive = false, morph = true },
        { offset = 294, name = "Lotus Flower", passive = false },
        { offset = 295, name = "Green Lotus", passive = false, morph = true },
        { offset = 296, name = "Lotus Blossom", passive = false, morph = true },
        { offset = 297, name = "Nature's Grasp", passive = false },
        { offset = 298, name = "Nature's Embrace", passive = false, morph = true },
        { offset = 299, name = "Bursting Vines", passive = false, morph = true },
        { offset = 300, name = "Accelerated Growth", passive = true },
        { offset = 301, name = "Nature's Gift", passive = true },
        { offset = 302, name = "Emerald Moss", passive = true },
        { offset = 303, name = "Maturation", passive = true },
    },
    ["Animal Companions"] = {
        { offset = 304, name = "Feral Guardian", passive = false, ultimate = true },
        { offset = 305, name = "Eternal Guardian", passive = false, morph = true },
        { offset = 306, name = "Wild Guardian", passive = false, morph = true },
        { offset = 307, name = "Dive", passive = false },
        { offset = 308, name = "Cutting Dive", passive = false, morph = true },
        { offset = 309, name = "Screaming Cliff Racer", passive = false, morph = true },
        { offset = 310, name = "Scorch", passive = false },
        { offset = 311, name = "Subterranean Assault", passive = false, morph = true },
        { offset = 312, name = "Deep Fissure", passive = false, morph = true },
        { offset = 313, name = "Swarm", passive = false },
        { offset = 314, name = "Fetcher Infection", passive = false, morph = true },
        { offset = 315, name = "Growing Swarm", passive = false, morph = true },
        { offset = 316, name = "Betty Netch", passive = false },
        { offset = 317, name = "Blue Betty", passive = false, morph = true },
        { offset = 318, name = "Bull Netch", passive = false, morph = true },
        { offset = 319, name = "Falcon's Swiftness", passive = false },
        { offset = 320, name = "Deceptive Predator", passive = false, morph = true },
        { offset = 321, name = "Bird of Prey", passive = false, morph = true },
        { offset = 322, name = "Bond with Nature", passive = true },
        { offset = 323, name = "Savage Beast", passive = true },
        { offset = 324, name = "Flourish", passive = true },
        { offset = 325, name = "Advanced Species", passive = true },
    },
    -- Necromancer Skills
    ["Grave Lord"] = {
        { offset = 326, name = "Frozen Colossus", passive = false, ultimate = true },
        { offset = 327, name = "Pestilent Colossus", passive = false, morph = true },
        { offset = 328, name = "Glacial Colossus", passive = false, morph = true },
        { offset = 329, name = "Flame Skull", passive = false },
        { offset = 330, name = "Venom Skull", passive = false, morph = true },
        { offset = 331, name = "Ricochet Skull", passive = false, morph = true },
        { offset = 332, name = "Blastbones", passive = false },
        { offset = 333, name = "Blighted Blastbones", passive = false, morph = true },
        { offset = 334, name = "Stalking Blastbones", passive = false, morph = true },
        { offset = 335, name = "Boneyard", passive = false },
        { offset = 336, name = "Unnerving Boneyard", passive = false, morph = true },
        { offset = 337, name = "Avid Boneyard", passive = false, morph = true },
        { offset = 338, name = "Skeletal Mage", passive = false },
        { offset = 339, name = "Skeletal Archer", passive = false, morph = true },
        { offset = 340, name = "Skeletal Arcanist", passive = false, morph = true },
        { offset = 341, name = "Shocking Siphon", passive = false },
        { offset = 342, name = "Detonating Siphon", passive = false, morph = true },
        { offset = 343, name = "Mystic Siphon", passive = false, morph = true },
        { offset = 344, name = "Reusable Parts", passive = true },
        { offset = 345, name = "Death Knell", passive = true },
        { offset = 346, name = "Dismember", passive = true },
        { offset = 347, name = "Rapid Rot", passive = true },
    },
    ["Bone Tyrant"] = {
        { offset = 348, name = "Bone Goliath", passive = false, ultimate = true },
        { offset = 349, name = "Pummeling Goliath", passive = false, morph = true },
        { offset = 350, name = "Ravenous Goliath", passive = false, morph = true },
        { offset = 351, name = "Death Scythe", passive = false },
        { offset = 352, name = "Ruinous Scythe", passive = false, morph = true },
        { offset = 353, name = "Hungry Scythe", passive = false, morph = true },
        { offset = 354, name = "Bone Armor", passive = false },
        { offset = 355, name = "Beckoning Armor", passive = false, morph = true },
        { offset = 356, name = "Summoner's Armor", passive = false, morph = true },
        { offset = 357, name = "Grave Grasp", passive = false },
        { offset = 358, name = "Ghostly Embrace", passive = false, morph = true },
        { offset = 359, name = "Empowering Grasp", passive = false, morph = true },
        { offset = 360, name = "Bitter Harvest", passive = false },
        { offset = 361, name = "Deaden Pain", passive = false, morph = true },
        { offset = 362, name = "Necrotic Potency", passive = false, morph = true },
        { offset = 363, name = "Bone Totem", passive = false },
        { offset = 364, name = "Remote Totem", passive = false, morph = true },
        { offset = 365, name = "Agony Totem", passive = false, morph = true },
        { offset = 366, name = "Death Gleaning", passive = true },
        { offset = 367, name = "Disdain Harm", passive = true },
        { offset = 368, name = "Health Avarice", passive = true },
        { offset = 369, name = "Last Gasp", passive = true },
    },
    ["Living Death"] = {
        { offset = 370, name = "Reanimate", passive = false, ultimate = true },
        { offset = 371, name = "Renewing Undeath", passive = false, morph = true },
        { offset = 372, name = "Animate Blastbones", passive = false, morph = true },
        { offset = 373, name = "Render Flesh", passive = false },
        { offset = 374, name = "Resistant Flesh", passive = false, morph = true },
        { offset = 375, name = "Blood Sacrifice", passive = false, morph = true },
        { offset = 376, name = "Expunge", passive = false },
        { offset = 377, name = "Expunge and Modify", passive = false, morph = true },
        { offset = 378, name = "Hexproof", passive = false, morph = true },
        { offset = 379, name = "Life Amid Death", passive = false },
        { offset = 380, name = "Renewing Undeath", passive = false, morph = true },
        { offset = 381, name = "Enduring Undeath", passive = false, morph = true },
        { offset = 382, name = "Spirit Mender", passive = false },
        { offset = 383, name = "Spirit Guardian", passive = false, morph = true },
        { offset = 384, name = "Intensive Mender", passive = false, morph = true },
        { offset = 385, name = "Restoring Tether", passive = false },
        { offset = 386, name = "Braided Tether", passive = false, morph = true },
        { offset = 387, name = "Mortal Coil", passive = false, morph = true },
        { offset = 388, name = "Curative Curse", passive = true },
        { offset = 389, name = "Near-Death Experience", passive = true },
        { offset = 390, name = "Corpse Consumption", passive = true },
        { offset = 391, name = "Undead Confederate", passive = true },
    },
    -- Arcanist Skills
    ["Herald of the Tome"] = {
        { offset = 392, name = "Fatecarver", passive = false, ultimate = true },
        { offset = 393, name = "Exhausting Fatecarver", passive = false, morph = true },
        { offset = 394, name = "Pragmatic Fatecarver", passive = false, morph = true },
        { offset = 395, name = "Runeblades", passive = false },
        { offset = 396, name = "Escalating Runeblades", passive = false, morph = true },
        { offset = 397, name = "Writhing Runeblades", passive = false, morph = true },
        { offset = 398, name = "Abyssal Impact", passive = false },
        { offset = 399, name = "Cephaliarch's Flail", passive = false, morph = true },
        { offset = 400, name = "Tentacular Dread", passive = false, morph = true },
        { offset = 401, name = "The Tide King's Gaze", passive = false },
        { offset = 402, name = "Languid Eye", passive = false, morph = true },
        { offset = 403, name = "Roaming Basilisk", passive = false, morph = true },
        { offset = 404, name = "Fulminating Rune", passive = false },
        { offset = 405, name = "Escalating Rune", passive = false, morph = true },
        { offset = 406, name = "Impervious Rune", passive = false, morph = true },
        { offset = 407, name = "Tome-Bearer's Inspiration", passive = false },
        { offset = 408, name = "Inspired Scholarship", passive = false, morph = true },
        { offset = 409, name = "Recuperative Treatise", passive = false, morph = true },
        { offset = 410, name = "Fated Fortune", passive = true },
        { offset = 411, name = "Harnessed Quintessence", passive = true },
        { offset = 412, name = "Hideous Clarity", passive = true },
        { offset = 413, name = "Psychic Lesion", passive = true },
    },
    ["Soldier of Apocrypha"] = {
        { offset = 414, name = "Gibbering Shield", passive = false, ultimate = true },
        { offset = 415, name = "Sanctum of the Abyssal Sea", passive = false, morph = true },
        { offset = 416, name = "Bastion of the Watcher", passive = false, morph = true },
        { offset = 417, name = "Runemend", passive = false },
        { offset = 418, name = "Evolving Runemend", passive = false, morph = true },
        { offset = 419, name = "Audacious Runemend", passive = false, morph = true },
        { offset = 420, name = "Runespite Ward", passive = false },
        { offset = 421, name = "Impervious Runeward", passive = false, morph = true },
        { offset = 422, name = "Spiteward of the Lucid Mind", passive = false, morph = true },
        { offset = 423, name = "Rune of Displacement", passive = false },
        { offset = 424, name = "Rune of Eldritch Horror", passive = false, morph = true },
        { offset = 425, name = "Rune of the Colorless Pool", passive = false, morph = true },
        { offset = 426, name = "Apocryphal Gate", passive = false },
        { offset = 427, name = "Passage Between Worlds", passive = false, morph = true },
        { offset = 428, name = "Fleet-Footed Gate", passive = false, morph = true },
        { offset = 429, name = "Reconstructive Domain", passive = false },
        { offset = 430, name = "Zenas's Empowering Disc", passive = false, morph = true },
        { offset = 431, name = "Famished Domain", passive = false, morph = true },
        { offset = 432, name = "Wellspring of the Abyss", passive = true },
        { offset = 433, name = "Aegis of the Unseen", passive = true },
        { offset = 434, name = "Honed Runeforms", passive = true },
        { offset = 435, name = "Runic Jolt", passive = true },
    },
    ["Curative Runeforms"] = {
        { offset = 436, name = "The Languid Eye", passive = false, ultimate = true },
        { offset = 437, name = "Tide King's Lure", passive = false, morph = true },
        { offset = 438, name = "Fate-Foretold Knell", passive = false, morph = true },
        { offset = 439, name = "Remedy Cascade", passive = false },
        { offset = 440, name = "Cascading Fortune", passive = false, morph = true },
        { offset = 441, name = "Soothing Cascade", passive = false, morph = true },
        { offset = 442, name = "Chakram Shields", passive = false },
        { offset = 443, name = "Spinning Chakram", passive = false, morph = true },
        { offset = 444, name = "Chakram of Destiny", passive = false, morph = true },
        { offset = 445, name = "Arcanist's Domain", passive = false },
        { offset = 446, name = "Vitalizing Glyphic", passive = false, morph = true },
        { offset = 447, name = "Rune of Preservation", passive = false, morph = true },
        { offset = 448, name = "Runic Sunder", passive = false },
        { offset = 449, name = "Splintering Sunder", passive = false, morph = true },
        { offset = 450, name = "Exhausted Sunder", passive = false, morph = true },
        { offset = 451, name = "Unblinking Eye", passive = false },
        { offset = 452, name = "Pragmatic Eye", passive = false, morph = true },
        { offset = 453, name = "Vigilant Eye", passive = false, morph = true },
        { offset = 454, name = "Healing Tides", passive = true },
        { offset = 455, name = "Erudition", passive = true },
        { offset = 456, name = "Circumvented Fate", passive = true },
        { offset = 457, name = "Deliberation", passive = true },
    },
    -- Weapon Skills
    ["Two Handed"] = {
        { offset = 458, name = "Berserker Strike", passive = false, ultimate = true },
        { offset = 459, name = "Onslaught", passive = false, morph = true },
        { offset = 460, name = "Berserker Rage", passive = false, morph = true },
        { offset = 461, name = "Uppercut", passive = false },
        { offset = 462, name = "Dizzying Swing", passive = false, morph = true },
        { offset = 463, name = "Wrecking Blow", passive = false, morph = true },
        { offset = 464, name = "Critical Charge", passive = false },
        { offset = 465, name = "Stampede", passive = false, morph = true },
        { offset = 466, name = "Critical Rush", passive = false, morph = true },
        { offset = 467, name = "Cleave", passive = false },
        { offset = 468, name = "Carve", passive = false, morph = true },
        { offset = 469, name = "Brawler", passive = false, morph = true },
        { offset = 470, name = "Reverse Slash", passive = false },
        { offset = 471, name = "Reverse Slice", passive = false, morph = true },
        { offset = 472, name = "Executioner", passive = false, morph = true },
        { offset = 473, name = "Momentum", passive = false },
        { offset = 474, name = "Forward Momentum", passive = false, morph = true },
        { offset = 475, name = "Rally", passive = false, morph = true },
        { offset = 476, name = "Forceful", passive = true },
        { offset = 477, name = "Heavy Weapons", passive = true },
        { offset = 478, name = "Balanced Blade", passive = true },
        { offset = 479, name = "Follow Up", passive = true },
        { offset = 480, name = "Battle Rush", passive = true },
    },
    ["One Hand and Shield"] = {
        { offset = 481, name = "Shield Wall", passive = false, ultimate = true },
        { offset = 482, name = "Spell Wall", passive = false, morph = true },
        { offset = 483, name = "Shield Discipline", passive = false, morph = true },
        { offset = 484, name = "Puncture", passive = false },
        { offset = 485, name = "Ransack", passive = false, morph = true },
        { offset = 486, name = "Pierce Armor", passive = false, morph = true },
        { offset = 487, name = "Low Slash", passive = false },
        { offset = 488, name = "Deep Slash", passive = false, morph = true },
        { offset = 489, name = "Heroic Slash", passive = false, morph = true },
        { offset = 490, name = "Defensive Posture", passive = false },
        { offset = 491, name = "Defensive Stance", passive = false, morph = true },
        { offset = 492, name = "Absorb Missile", passive = false, morph = true },
        { offset = 493, name = "Shield Charge", passive = false },
        { offset = 494, name = "Shielded Assault", passive = false, morph = true },
        { offset = 495, name = "Invasion", passive = false, morph = true },
        { offset = 496, name = "Power Bash", passive = false },
        { offset = 497, name = "Reverberating Bash", passive = false, morph = true },
        { offset = 498, name = "Power Slam", passive = false, morph = true },
        { offset = 499, name = "Fortress", passive = true },
        { offset = 500, name = "Sword and Board", passive = true },
        { offset = 501, name = "Deadly Bash", passive = true },
        { offset = 502, name = "Deflect Bolts", passive = true },
        { offset = 503, name = "Battlefield Mobility", passive = true },
    },
    ["Dual Wield"] = {
        { offset = 504, name = "Lacerate", passive = false, ultimate = true },
        { offset = 505, name = "Rend", passive = false, morph = true },
        { offset = 506, name = "Thrive in Chaos", passive = false, morph = true },
        { offset = 507, name = "Flurry", passive = false },
        { offset = 508, name = "Rapid Strikes", passive = false, morph = true },
        { offset = 509, name = "Bloodthirst", passive = false, morph = true },
        { offset = 510, name = "Twin Slashes", passive = false },
        { offset = 511, name = "Rending Slashes", passive = false, morph = true },
        { offset = 512, name = "Blood Craze", passive = false, morph = true },
        { offset = 513, name = "Whirlwind", passive = false },
        { offset = 514, name = "Whirling Blades", passive = false, morph = true },
        { offset = 515, name = "Steel Tornado", passive = false, morph = true },
        { offset = 516, name = "Blade Cloak", passive = false },
        { offset = 517, name = "Quick Cloak", passive = false, morph = true },
        { offset = 518, name = "Deadly Cloak", passive = false, morph = true },
        { offset = 519, name = "Hidden Blade", passive = false },
        { offset = 520, name = "Flying Blade", passive = false, morph = true },
        { offset = 521, name = "Shrouded Daggers", passive = false, morph = true },
        { offset = 522, name = "Slaughter", passive = true },
        { offset = 523, name = "Dual Wield Expert", passive = true },
        { offset = 524, name = "Controlled Fury", passive = true },
        { offset = 525, name = "Ruffian", passive = true },
        { offset = 526, name = "Twin Blade and Blunt", passive = true },
    },
    ["Bow"] = {
        { offset = 527, name = "Rapid Fire", passive = false, ultimate = true },
        { offset = 528, name = "Toxic Barrage", passive = false, morph = true },
        { offset = 529, name = "Ballista", passive = false, morph = true },
        { offset = 530, name = "Snipe", passive = false },
        { offset = 531, name = "Lethal Arrow", passive = false, morph = true },
        { offset = 532, name = "Focused Aim", passive = false, morph = true },
        { offset = 533, name = "Volley", passive = false },
        { offset = 534, name = "Endless Hail", passive = false, morph = true },
        { offset = 535, name = "Arrow Barrage", passive = false, morph = true },
        { offset = 536, name = "Scatter Shot", passive = false },
        { offset = 537, name = "Magnum Shot", passive = false, morph = true },
        { offset = 538, name = "Draining Shot", passive = false, morph = true },
        { offset = 539, name = "Arrow Spray", passive = false },
        { offset = 540, name = "Bombard", passive = false, morph = true },
        { offset = 541, name = "Acid Spray", passive = false, morph = true },
        { offset = 542, name = "Poison Arrow", passive = false },
        { offset = 543, name = "Venom Arrow", passive = false, morph = true },
        { offset = 544, name = "Poison Injection", passive = false, morph = true },
        { offset = 545, name = "Long Shots", passive = true },
        { offset = 546, name = "Accuracy", passive = true },
        { offset = 547, name = "Ranger", passive = true },
        { offset = 548, name = "Hawk Eye", passive = true },
        { offset = 549, name = "Hasty Retreat", passive = true },
    },
    ["Destruction Staff"] = {
        { offset = 550, name = "Elemental Storm", passive = false, ultimate = true },
        { offset = 551, name = "Elemental Rage", passive = false, morph = true },
        { offset = 552, name = "Eye of the Storm", passive = false, morph = true },
        { offset = 553, name = "Force Shock", passive = false },
        { offset = 554, name = "Crushing Shock", passive = false, morph = true },
        { offset = 555, name = "Force Pulse", passive = false, morph = true },
        { offset = 556, name = "Wall of Elements", passive = false },
        { offset = 557, name = "Unstable Wall of Elements", passive = false, morph = true },
        { offset = 558, name = "Elemental Blockade", passive = false, morph = true },
        { offset = 559, name = "Destructive Touch", passive = false },
        { offset = 560, name = "Destructive Clench", passive = false, morph = true },
        { offset = 561, name = "Destructive Reach", passive = false, morph = true },
        { offset = 562, name = "Weakness to Elements", passive = false },
        { offset = 563, name = "Elemental Susceptibility", passive = false, morph = true },
        { offset = 564, name = "Elemental Drain", passive = false, morph = true },
        { offset = 565, name = "Impulse", passive = false },
        { offset = 566, name = "Elemental Ring", passive = false, morph = true },
        { offset = 567, name = "Pulsar", passive = false, morph = true },
        { offset = 568, name = "Tri Focus", passive = true },
        { offset = 569, name = "Penetrating Magic", passive = true },
        { offset = 570, name = "Elemental Force", passive = true },
        { offset = 571, name = "Ancient Knowledge", passive = true },
        { offset = 572, name = "Destruction Expert", passive = true },
    },
    ["Restoration Staff"] = {
        { offset = 573, name = "Panacea", passive = false, ultimate = true },
        { offset = 574, name = "Life Giver", passive = false, morph = true },
        { offset = 575, name = "Light's Champion", passive = false, morph = true },
        { offset = 576, name = "Grand Healing", passive = false },
        { offset = 577, name = "Illustrious Healing", passive = false, morph = true },
        { offset = 578, name = "Healing Springs", passive = false, morph = true },
        { offset = 579, name = "Regeneration", passive = false },
        { offset = 580, name = "Rapid Regeneration", passive = false, morph = true },
        { offset = 581, name = "Radiating Regeneration", passive = false, morph = true },
        { offset = 582, name = "Blessing of Protection", passive = false },
        { offset = 583, name = "Blessing of Restoration", passive = false, morph = true },
        { offset = 584, name = "Combat Prayer", passive = false, morph = true },
        { offset = 585, name = "Steadfast Ward", passive = false },
        { offset = 586, name = "Ward Ally", passive = false, morph = true },
        { offset = 587, name = "Healing Ward", passive = false, morph = true },
        { offset = 588, name = "Force Siphon", passive = false },
        { offset = 589, name = "Siphon Spirit", passive = false, morph = true },
        { offset = 590, name = "Quick Siphon", passive = false, morph = true },
        { offset = 591, name = "Essence Drain", passive = true },
        { offset = 592, name = "Restoration Expert", passive = true },
        { offset = 593, name = "Cycle of Life", passive = true },
        { offset = 594, name = "Absorb", passive = true },
        { offset = 595, name = "Restoration Master", passive = true },
    },
    -- Armor Skills
    ["Light Armor"] = {
        { offset = 596, name = "Annulment", passive = false },
        { offset = 597, name = "Dampen Magic", passive = false, morph = true },
        { offset = 598, name = "Harness Magicka", passive = false, morph = true },
        { offset = 599, name = "Grace", passive = true },
        { offset = 600, name = "Evocation", passive = true },
        { offset = 601, name = "Spell Warding", passive = true },
        { offset = 602, name = "Prodigy", passive = true },
        { offset = 603, name = "Concentration", passive = true },
    },
    ["Medium Armor"] = {
        { offset = 604, name = "Evasion", passive = false },
        { offset = 605, name = "Shuffle", passive = false, morph = true },
        { offset = 606, name = "Elude", passive = false, morph = true },
        { offset = 607, name = "Dexterity", passive = true },
        { offset = 608, name = "Wind Walker", passive = true },
        { offset = 609, name = "Improved Sneak", passive = true },
        { offset = 610, name = "Agility", passive = true },
        { offset = 611, name = "Athletics", passive = true },
    },
    ["Heavy Armor"] = {
        { offset = 612, name = "Immovable", passive = false },
        { offset = 613, name = "Immovable Brute", passive = false, morph = true },
        { offset = 614, name = "Unstoppable", passive = false, morph = true },
        { offset = 615, name = "Resolve", passive = true },
        { offset = 616, name = "Constitution", passive = true },
        { offset = 617, name = "Juggernaut", passive = true },
        { offset = 618, name = "Revitalize", passive = true },
        { offset = 619, name = "Rapid Mending", passive = true },
    },
    -- Guild Skills
    ["Fighters Guild"] = {
        { offset = 720, name = "Dawnbreaker", passive = false, ultimate = true },
        { offset = 721, name = "Flawless Dawnbreaker", passive = false, morph = true },
        { offset = 722, name = "Dawnbreaker of Smiting", passive = false, morph = true },
        { offset = 723, name = "Silver Bolts", passive = false },
        { offset = 724, name = "Silver Shards", passive = false, morph = true },
        { offset = 725, name = "Silver Leash", passive = false, morph = true },
        { offset = 726, name = "Circle of Protection", passive = false },
        { offset = 727, name = "Turn Undead", passive = false, morph = true },
        { offset = 728, name = "Ring of Preservation", passive = false, morph = true },
        { offset = 729, name = "Expert Hunter", passive = false },
        { offset = 730, name = "Evil Hunter", passive = false, morph = true },
        { offset = 731, name = "Camouflaged Hunter", passive = false, morph = true },
        { offset = 732, name = "Trap Beast", passive = false },
        { offset = 733, name = "Rearming Trap", passive = false, morph = true },
        { offset = 734, name = "Lightweight Beast Trap", passive = false, morph = true },
        { offset = 735, name = "Skilled Tracker", passive = true },
        { offset = 736, name = "Bounty Hunter", passive = true },
        { offset = 737, name = "Slayer", passive = true },
        { offset = 738, name = "Banish the Wicked", passive = true },
        { offset = 739, name = "Destroyer", passive = true },
    },
    ["Mages Guild"] = {
        { offset = 740, name = "Meteor", passive = false, ultimate = true },
        { offset = 741, name = "Ice Comet", passive = false, morph = true },
        { offset = 742, name = "Shooting Star", passive = false, morph = true },
        { offset = 743, name = "Magelight", passive = false },
        { offset = 744, name = "Inner Light", passive = false, morph = true },
        { offset = 745, name = "Radiant Magelight", passive = false, morph = true },
        { offset = 746, name = "Entropy", passive = false },
        { offset = 747, name = "Degeneration", passive = false, morph = true },
        { offset = 748, name = "Structured Entropy", passive = false, morph = true },
        { offset = 749, name = "Fire Rune", passive = false },
        { offset = 750, name = "Volcanic Rune", passive = false, morph = true },
        { offset = 751, name = "Scalding Rune", passive = false, morph = true },
        { offset = 752, name = "Equilibrium", passive = false },
        { offset = 753, name = "Spell Symmetry", passive = false, morph = true },
        { offset = 754, name = "Balance", passive = false, morph = true },
        { offset = 755, name = "Persuasive Will", passive = true },
        { offset = 756, name = "Mage Adept", passive = true },
        { offset = 757, name = "Everlasting Magic", passive = true },
        { offset = 758, name = "Magicka Controller", passive = true },
        { offset = 759, name = "Might of the Guild", passive = true },
    },
}

-- Helper function to get skill info by item ID
function APESO_SkillData.GetSkillByItemId(itemId)
    local baseId = 152100
    local offset = itemId - baseId

    for categoryName, skills in pairs(APESO_SkillData.Categories) do
        for _, skill in ipairs(skills) do
            if skill.offset == offset then
                return skill, categoryName
            end
        end
    end

    return nil, nil
end

-- Helper function to get all skills in a category
function APESO_SkillData.GetSkillsInCategory(categoryName)
    return APESO_SkillData.Categories[categoryName] or {}
end
